# Generated by Django 2.2.2 on 2019-06-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_auto_20190610_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='doc_ident',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
