# Generated by Django 2.2.2 on 2019-07-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spwm_pipe_cleaning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decapcarb',
            name='Produto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
