# Generated by Django 2.2.2 on 2019-06-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spwm_welding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wps',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
