# Generated by Django 2.2.2 on 2019-07-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spwm_welding', '0002_auto_20190630_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='wps',
            name='Produto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
