# Generated by Django 2.2.2 on 2019-06-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_auto_20190607_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='proprietariopf',
            new_name='proprietario',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='proprietariopj',
        ),
    ]
