# Generated by Django 2.2.2 on 2019-06-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_auto_20190611_1234'),
        ('registro_hora_extra', '0003_registro_hora_extra_horas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro_Hora_Extra',
            new_name='RegistroHoraExtra',
        ),
    ]
